name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup node
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 24.6.0
          cache: 'npm'
      - run: npm i
      - run: npm run test


